### PR TITLE
[DOCS] rely on helpers directly and use positional syntax

### PR DESCRIPTION
**Pull request by rgbkrk**
Follow up from #14 mostly, changing the syntax for the README.

Side question: How bad would it be if we always provide the helpers at the top level from `vdom`?

### CODE REVIEW

**Comment by willingc** [comment]
Side question: How bad would it be if we always provide the helpers at the top level from vdom?

I don't know. What are the pros/cons?

**Comment by rgbkrk** [comment]
I was trying to keep the surface area small, thinking people would use `createComponent`. Then I noticed I pretty much always just use all the helper functions `p`, `div`, etc. Either way we have to maintain the interfaces so I can't really discount it for maintainability.

Providing the helpers from the top level --

Pros:

* Super easy to write about and show others `from vdom import h1, div, p, img`
* Less to explain within documentation about why we'd have `core`, `helpers`, etc., just one nice top level package namespace to teach and use

Cons:

* "pollutes" the top level namespace, making it have a lot more at the top level module
* The current `vdom` only provides what's in core right now, so it's much lighter to load up than the now 81+ helpers we'd be adding on (in the grand scheme of things though, this is pretty darn small)

While I've written two cons, they're pretty much a non-issue for runtime size. These are tiny little classes and they share a lot of functionality. I think the dev experience will be much better if the most common functions are at the top.

**Comment by willingc** [comment]
I think you just answered your own question ;-)

**Comment by rgbkrk** [comment]
Thanks. 😄

**Pull request merged**
