### PR TITLE
Add event handler support

### PR DESCRIPTION
**Pull request by gnestor**
Proposal:

```py
from vdom.helpers import *

# Create a label that will display the counter value
label_value = 1
my_label = label(str(label_value))

# Create an event handler
def handle_click():
    global label_value
    label_value += 1
    my_label.update(str(label_value))

# Create a button that will increment the counter value
my_button = button(name='my_button', onClick=lambda event: handle_click())

div(my_label, my_button)
```

On the kernel-side, for any attribute whose value is a function (e.g. `handle_click` above): 

* A comm channel will be opened using the `target_name` (which defaults to the hash of the callback function e.g. `str(hash(handle_click))`)
* The attribute value will be replaced with a JSON representation of the callback function (that could look like `{ target_name: taget_name }`)
* When a message is received over that comm channel, it will call the callback function with the value of the message, which will be a JSON representation of the DOM event
  * In most cases, this callback function should update the state on the client by calling `update_display` or using a new `update` method on the component that's introduced in this PR (essentially calls `__init__` on the component class **except** it preserves its `_display_id` property value)

On the client-side (jupyterlab PR coming soon), for any attribute whos value is a JSON representation of a callback function (e.g. has a `target_name` key):

* The client will connect to the comm channel using the `target_name`
* The attribute value will be replaced with a JS callback function that will send a JSON representation of the DOM event to the kernel over the comm channel
* The callback function on the kernel will be used to handle the event

### CODE REVIEW

**Comment by gnestor** [comment]
Related work: https://github.com/nteract/nteract/pull/1907

**Comment by rgbkrk** [comment]
It's sure been a while, I think it's time for us to sync on this! How have you been, got any free time to chat @gnestor?

**Comment by gnestor** [comment]
@rgbkrk Yes!! I haven't had time to work on this since but I would LOVE to get it across the finish line.

**Comment by rgbkrk** [comment]
Cool, I've set a meeting up for 3 pm Pacific Time. Others can join as well if they'd like -- just ping me direct or in an issue.

**Comment by gnestor** [comment]
This is currently working in JupyterLab with this PR on jupyter-renderers: https://github.com/jupyterlab/jupyter-renderers/pull/134

You can try them together using this binder: https://mybinder.org/v2/gh/gnestor/jupyter-renderers/vdom-experimental?urlpath=lab/tree/notebooks/vdom-experimental-extension.ipynb

More info at https://github.com/gnestor/jupyter-renderers/tree/vdom-experimental/packages/vdom-experimental-extension

**Comment by gnestor** [comment]
I added a first draft of the event handler/event object spec: https://github.com/gnestor/vdom/blob/d94cb7d05e4349fa9fbe633ca561abf3d9092484/docs/event-spec.md

**Comment by gnestor** [comment]
I added an event handler section to the spec: https://github.com/nteract/vdom/blob/1887c6b6114bc683a933ac98fa2257d5bdf602c1/docs/event-spec.md

@rgbkrk @mpacer Can you review the spec? It could probably be reworded in parts...

**Comment by rgbkrk** [comment]
I think this is looking pretty good and we should move forward on iterating with it. We're also waiting on  #68 (though just a fix to a test). I want you to be able to keep moving this forward, since I know you'll be back to keep maintaining it.

**Pull request merged**
